#!/bin/sh

################################################################################
# Version 1.3.0-RELEASE (15-01-2022)
################################################################################

################################################################################
# Copyright 2019-2022 Nozel/Sebas Veeke. Licenced under a Creative Commons
# Attribution-NonCommercial-ShareAlike 4.0 International License.
#
# See https://creativecommons.org/licenses/by-nc-sa/4.0/
#
# Contact:
# > e-mail      mail@nozel.org
# > GitHub      onnozel
################################################################################

################################################################################
# VARIABLES
################################################################################

# serverbot version
BACKUPBOT_VERSION='1.3.0'

# backupbot parameters can be configured in /usr/local/etc/backupbot.conf
# if the backupbot configuration file exists, it gets sourced by backupbot
if [ -f /usr/local/etc/backupbot.conf ]; then
    # populate all usable variables for checking validity later on
    AUTOMATIC_BACKUP_ENABLE='0'
    AUTOMATIC_BACKUP_CRON='0'
    BACKUP_ENCRYPTION='0'
    BACKUP_ENCRYPTION_SECRET='0'
    BACKUP_FILES_ENABLE='0'
    BACKUP_FILES_PREFIX='0'
    BACKUP_FILES_RETENTION='0'
    BACKUP_FILES_COMPRESSION='0'
    BACKUP_FILES_DESTINATION='0'
    BACKUP_FILES='0'
    BACKUP_MYSQL_ENABLE='0'
    BACKUP_MYSQL_PREFIX='0'
    BACKUP_MYSQL_RETENTION='0'
    BACKUP_MYSQL_COMPRESSION='0'
    BACKUP_MYSQL_DESTINATION='0'

    # and source backupbot.conf
    . /usr/local/etc/backupbot.conf

    # and finally use default values for unconfigured parameters
    if [ "${BACKUP_FILES_PREFIX}" = '0' ]; then
        BACKUP_FILES_PREFIX="$(date +%y%m%dT%H%M)"
    fi
    if [ "${BACKUP_MYSQL_PREFIX}" = '0' ]; then
        BACKUP_MYSQL_PREFIX="$(date +%y%m%dT%H%M)"
    fi
else
    # if backupbot.conf does not exist, return this error 
    echo 'backupbot: error: /usr/local/etc/backupbot.conf is required but cannot be found'
    exit 1
fi

################################################################################
# ARGUMENTS
################################################################################

# enable arguments to backupbot
while test -n "$1"; do
    case "$1" in
        # options
        --version)
            ARGUMENT_VERSION='1'
            shift
            ;;

        --help|-help|help|--h|-h)
            ARGUMENT_HELP='1'
            shift
            ;;

        --cron)
            ARGUMENT_CRON='1'
            shift
            ;;

        # features
        --backup|backup|-b)
            ARGUMENT_BACKUP='1'
            shift
            ;;

        --files|files|-f)
            ARGUMENT_FILES='1'
            shift
            ;;

        --mysql|mysql|-m)
            ARGUMENT_MYSQL='1'
            shift
            ;;

        # other
        *)
            ARGUMENT_NONE='1'
            shift
            ;;
    esac
done

################################################################################
# ERROR FUNCTIONS
################################################################################

# requirement errors
error_invalid_argument() {
    echo 'backupbot: error: used argument is invalid, use "backuptbot --help" for proper usage'
    exit 1
}    

error_no_root_privileges() {
    echo 'backupbot: error: used argument must be run with root privileges'
    exit 1
}

error_os_not_supported() {
    echo 'backupbot: operating system is not supported'
    exit 1
}

# configuration errors
error_destination_not_configured() {
    echo 'backupbot: error: backup destination is not configured properly in /usr/local/etc/backupbot.conf'
    exit 1
}

error_source_not_configured() {
    echo 'backupbot: error: backup source is not configured properly in /usr/local/etc/backupbot.conf'
    exit 1
}

error_cron_not_configured() {
    echo 'backupbot: error: cron is not configured properly in /usr/local/etc/backupbot.conf'
    exit 1
}

error_no_feature_configured() {
    echo 'backupbot: error: no backup feature is enabled in /usr/local/etc/backupbot.conf'
    exit 1
}

error_retention_not_integer() {
    echo 'backupbot: error: retention should be a positive number in /usr/local/etc/backupbot.conf'
    exit 1
}

error_feature_not_configured() {
    echo 'backupbot: error: one of the invoked features is not configured in /usr/local/etc/backupbot.conf'
    exit 1
}

error_gpg_not_installed() {
    echo 'backupbot: error: gpg is required but not installed'
    echo 'backupbot: install gpg with "pkg install gnupg"'
    exit 1
}

error_compression_not_configured() {
    echo 'backupbot: error: compression is not configured properly in /usr/local/etc/backupbot.conf'
    exit 1
}

################################################################################
# REQUIREMENT FUNCTIONS
################################################################################

requirement_argument_validity() {
    # enabled backup features must have file destinations
    if [ "${BACKUP_FILES_ENABLE}" = 'YES' ] && [ "${BACKUP_FILES_DESTINATION}" = '0' ]; then
        error_destination_not_configured
    fi
    if [ "${BACKUP_MYSQL_ENABLE}" = 'YES' ] && [ "${BACKUP_MYSQL_DESTINATION}" = '0' ]; then
        error_destination_not_configured
    fi
    # enabled backup features must have configured file sources
    if [ "${BACKUP_FILES_ENABLE}" = 'YES' ] && [ "${BACKUP_FILES}" = '0' ]; then
        error_source_not_configured
    fi
    # enabled automatic backup must have a configured cron parameter
    if [ "${AUTOMATIC_BACKUP_ENABLE}" = 'YES' ] && [ "${AUTOMATIC_BACKUP_CRON}" = '0' ]; then
        error_cron_not_configured
    fi
    # at least one backup feature must be enabled
    if [ "${BACKUP_FILES_ENABLE}" = '0' ] && [ "${BACKUP_MYSQL_ENABLE}" = '0' ]; then
        error_no_feature_configured
    fi
    # backup feature retention must be a integer
    if ! [ "${BACKUP_FILES_RETENTION}" -eq "${BACKUP_FILES_RETENTION}" ] 2> /dev/null; then
        error_retention_not_integer
    fi
    if ! [ "${BACKUP_MYSQL_RETENTION}" -eq "${BACKUP_MYSQL_RETENTION}" ] 2> /dev/null; then
        error_retention_not_integer
    fi
    # compression feature number must be 0, 2, 3 or 4
    if [ "${BACKUP_FILES_COMPRESSION}" != '0' ] && [ "${BACKUP_FILES_COMPRESSION}" != '1' ] && [ "${BACKUP_FILES_COMPRESSION}" != '2' ] && [ "${BACKUP_FILES_COMPRESSION}" != '3' ]; then
        error_compression_not_configured
    fi
}

requirement_root() {
    # show error when backupbot isn't run with root privileges
    if [ "$(id -u)" -ne '0' ]; then
        error_no_root_privileges
    fi
}

requirement_os() {
    # show error when freebsd-version cannot be found
    if [ ! "$(command -v freebsd-version)" ]; then
        error_os_not_supported
    fi
}

requirement_gpg() {
    # show error when gpg cannot be found
    if [ ! "$(command -v gpg)" ]; then
        error_gpg_not_installed
    fi
}

################################################################################
# GENERAL FUNCTIONS
################################################################################

option_version() {
    echo "Backupbot ${BACKUPBOT_VERSION}"
    echo "Copyright (C) 2019-2022 Nozel."
    echo "License CC Attribution-NonCommercial-ShareAlike 4.0 Int."
    echo
    echo "Written by Sebas Veeke"
}

option_help() {
    echo "Usage:"
    echo " backupbot [feature/option]..."
    echo
    echo "Features:"
    echo " -b, --backup         Backup everything configured in configuration file"
    echo " -f, --files          Backup files configured in configuration file"
    echo " -m, --mysql          Backup MySQL databases configured in configuration file"
    echo
    echo "Options:"
    echo " --cron               Effectuate cron changes from serverbot config"
    echo " --help               Display this help and exit"
    echo " --version            Display version information and exit"
}

option_cron() {
    echo 'Removing old backupbot cronjob'
    rm -f /etc/cron.d/backupbot
    if [ "${AUTOMATIC_BACKUP_ENABLE}" = 'YES' ]; then
        echo 'Updating cronjob for backupbot'
        echo '# This cronjob activates backupbot on the chosen schedule' > /etc/cron.d/backupbot
        echo "${AUTOMATIC_BACKUP_CRON} root /usr/bin/backupbot --backup" >> /etc/cron.d/backupbot
    else
        echo 'Automatic backup is disabled, skipping creation of cronjob'
    fi
    echo 'Done!'
}

################################################################################
# FEATURE FUNCTIONS
################################################################################

# the following settings are used for tar:
# --create               (-c) create new archive containing the specified items
# --preserve-permissions (-p) preserve file permissions
# --gzip                 (-z) compress the resulting archive with gunzip
# --bzip2                (-j) compress the resulting archive with bzip2
# --xz                   (-J) compress the resulting archive with xz
# --file -               (-f) pipe the archive to next command
# --verbose              (-v) produce verbose output (disabled by default)

# the following settings are used for gpg:
# --symmetric            (-c) use symmetric cipher for encryption
# --cipher-algo AES256        use AES256 as cipher algorithm
# --batch                     non-interactive mode
# --passphrase                use password provided in backupbot.conf
# --output               (-o) write output to file

# the following settings are used for mysqldump
# --single-transaction        dumps all tables in a single transaction

feature_files() {
    if [ "${BACKUP_FILES_ENABLE}" = 'YES' ]; then
        # check configured backup compression and create variables for arguments and file extension
        if [ "${BACKUP_FILES_COMPRESSION}" = '0' ]; then
            TAR_COMPRESSION_ARGUMENT=''
            FILES_FILE_EXTENSION='tar'
        elif [ "${BACKUP_FILES_COMPRESSION}" = '1' ]; then
            TAR_COMPRESSION_ARGUMENT='--gzip'
            FILES_FILE_EXTENSION='tar.gz'
        elif [ "${BACKUP_FILES_COMPRESSION}" = '2' ]; then
            TAR_COMPRESSION_ARGUMENT='--bzip2'
            FILES_FILE_EXTENSION='tar.bz2'
        elif [ "${BACKUP_FILES_COMPRESSION}" = '3' ]; then
            TAR_COMPRESSION_ARGUMENT='--xz'
            FILES_FILE_EXTENSION='tar.xz'
        fi

        # check whether backup encryption is enabled
        if [ "${BACKUP_ENCRYPTION}" = 'YES' ]; then
            requirement_gpg
            tar --create --preserve-permissions ${TAR_COMPRESSION_ARGUMENT} --file - ${BACKUP_FILES} | gpg --symmetric --cipher-algo AES256 --batch --passphrase "${BACKUP_ENCRYPTION_SECRET}" > "${BACKUP_FILES_DESTINATION}/${BACKUP_FILES_PREFIX}-files.${FILES_FILE_EXTENSION}.gpg"
        else
            tar --create --preserve-permissions ${TAR_COMPRESSION_ARGUMENT} --file "${BACKUP_FILES_DESTINATION}/${BACKUP_FILES_PREFIX}-files.${FILES_FILE_EXTENSION}" ${BACKUP_FILES}
        fi

        # delete backups older than file retention, unless it's zero (infinite)
        if [ "${BACKUP_FILES_RETENTION}" -gt '0' ]; then
            find "${BACKUP_FILES_DESTINATION}/" -type f -mtime +"${BACKUP_FILES_RETENTION}" -name '*files.tar' -delete
            find "${BACKUP_FILES_DESTINATION}/" -type f -mtime +"${BACKUP_FILES_RETENTION}" -name '*files.tar.gz' -delete
            find "${BACKUP_FILES_DESTINATION}/" -type f -mtime +"${BACKUP_FILES_RETENTION}" -name '*files.tar.bz2' -delete
            find "${BACKUP_FILES_DESTINATION}/" -type f -mtime +"${BACKUP_FILES_RETENTION}" -name '*files.tar.xz' -delete
            find "${BACKUP_FILES_DESTINATION}/" -type f -mtime +"${BACKUP_FILES_RETENTION}" -name '*files.tar.gpg' -delete
            find "${BACKUP_FILES_DESTINATION}/" -type f -mtime +"${BACKUP_FILES_RETENTION}" -name '*files.tar.gz.gpg' -delete
            find "${BACKUP_FILES_DESTINATION}/" -type f -mtime +"${BACKUP_FILES_RETENTION}" -name '*files.tar.bz2.gpg' -delete
            find "${BACKUP_FILES_DESTINATION}/" -type f -mtime +"${BACKUP_FILES_RETENTION}" -name '*files.tar.xz.gpg' -delete
        fi
    fi
}

feature_mysql() {
    if [ "${BACKUP_MYSQL_ENABLE}" = 'YES' ]; then
        # check configured backup compression and create variables for arguments and file extension
        if [ "${BACKUP_MYSQL_COMPRESSION}" = '0' ]; then
            MYSQL_COMPRESSION_ARGUMENT='cat'
            MYSQL_FILE_EXTENSION='sql'
        elif [ "${BACKUP_MYSQL_COMPRESSION}" = '1' ]; then
            MYSQL_COMPRESSION_ARGUMENT='gzip'
            MYSQL_FILE_EXTENSION='sql.gz'
        elif [ "${BACKUP_MYSQL_COMPRESSION}" = '2' ]; then
            MYSQL_COMPRESSION_ARGUMENT='bzip2'
            MYSQL_FILE_EXTENSION='sql.bz2'
        elif [ "${BACKUP_MYSQL_COMPRESSION}" = '3' ]; then
            MYSQL_COMPRESSION_ARGUMENT='xz'
            MYSQL_FILE_EXTENSION='sql.xz'
        fi

        # check whether backup encryption is enabled
        if [ "${BACKUP_ENCRYPTION}" = 'YES' ]; then
            requirement_gpg
            # create a list of all user created mysql databases and mysqldump them to their own file
            for DB in $(mysql -e 'show databases' -s --skip-column-names | sed '/performance_schema/d' | sed '/information_schema/d' | sed '/mysql/d'); do
                mysqldump --single-transaction "${DB}" | ${MYSQL_COMPRESSION_ARGUMENT} | gpg --symmetric --cipher-algo AES256 --batch --passphrase "${BACKUP_ENCRYPTION_SECRET}" > "${BACKUP_MYSQL_DESTINATION}/${BACKUP_MYSQL_PREFIX}-${DB}.${MYSQL_FILE_EXTENSION}.gpg"
            done
        else
            # create a list of all user created mysql databases and mysqldump them to their own file
            for DB in $(mysql -e 'show databases' -s --skip-column-names | sed '/performance_schema/d' | sed '/information_schema/d' | sed '/mysql/d'); do
                mysqldump --single-transaction "${DB}" | ${MYSQL_COMPRESSION_ARGUMENT} > "${BACKUP_MYSQL_DESTINATION}/${BACKUP_MYSQL_PREFIX}-${DB}.${MYSQL_FILE_EXTENSION}"
            done
        fi

        # delete backups older than mysql retention, unless it's zero (infinite)
        if [ "${BACKUP_MYSQL_RETENTION}" -gt '0' ]; then
            find "${BACKUP_MYSQL_DESTINATION}/" -type f -mtime +"${BACKUP_MYSQL_RETENTION}" -name '*sql' -delete
            find "${BACKUP_MYSQL_DESTINATION}/" -type f -mtime +"${BACKUP_MYSQL_RETENTION}" -name '*sql.gz' -delete
            find "${BACKUP_MYSQL_DESTINATION}/" -type f -mtime +"${BACKUP_MYSQL_RETENTION}" -name '*sql.bz2' -delete
            find "${BACKUP_MYSQL_DESTINATION}/" -type f -mtime +"${BACKUP_MYSQL_RETENTION}" -name '*sql.xz' -delete
            find "${BACKUP_MYSQL_DESTINATION}/" -type f -mtime +"${BACKUP_MYSQL_RETENTION}" -name '*sql.gpg' -delete
            find "${BACKUP_MYSQL_DESTINATION}/" -type f -mtime +"${BACKUP_MYSQL_RETENTION}" -name '*sql.gz.gpg' -delete
            find "${BACKUP_MYSQL_DESTINATION}/" -type f -mtime +"${BACKUP_MYSQL_RETENTION}" -name '*sql.bz2.gpg' -delete
            find "${BACKUP_MYSQL_DESTINATION}/" -type f -mtime +"${BACKUP_MYSQL_RETENTION}" -name '*sql.xz.gpg' -delete
        fi
    fi
}

################################################################################
# MAIN FUNCTION
################################################################################

backupbot_main() {
    # check whether requirements are met
    requirement_argument_validity

    # call option based on arguments
    if [ "${ARGUMENT_VERSION}" = '1' ]; then
        option_version
        exit 0
    elif [ "${ARGUMENT_HELP}" = '1' ]; then
        option_help
        exit 0
    elif [ "${ARGUMENT_CRON}" = '1' ]; then
        requirement_root
        requirement_os
        option_cron
        exit 0
    # call feature based on arguments
    elif [ "${ARGUMENT_BACKUP}" = '1' ]; then
        requirement_root
        requirement_os
        feature_files
        feature_mysql
        exit 0
    elif [ "${ARGUMENT_FILES}" = '1' ]; then
        requirement_root
        requirement_os
        feature_files
        exit 0
    elif [ "${ARGUMENT_MYSQL}" = '1' ]; then
        requirement_root
        requirement_os
        feature_mysql
        exit 0
    # return error on invalid argument
    elif [ "${ARGUMENT_NONE}" = '1' ]; then
        error_invalid_argument
    fi
}

# call main function
backupbot_main
